tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'
github:
  prebuilds:
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addBadge: true