tasks:
  - init: |
      echo 'Setting UP D100'
    command: npx -y serve
github:
  prebuilds:
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addBadge: true